server:
  port: 8081

spring:
  application:
    name: dataStructure
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect